line-length = 132

exclude = [
    # Without this, ruff format rewrites the Python code blocks in the docs sources under
    # templates/docs/.
    "*.md",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[lint]
select = [
    "F", "E", "W", "I", "UP", "C4", "B", "DTZ", "DJ", "RET", "SIM", "PIE", "PERF", "PTH", "RUF",
    "N", "A", "ERA", "ISC", "ICN", "TID", "TD", "PGH", "G", "LOG", "BLE",
]
ignore = [
    "E501",
    "ISC001",
    "RUF012",
    "RUF001",
    "RUF003",
]

[lint.isort]
required-imports = ["from __future__ import annotations"]

[lint.pep8-naming]
extend-ignore-names = ["assertEmail*"]
