line-length = 132

exclude = [
    # Without this, ruff format rewrites the Python code blocks in the docs sources under
    # templates/docs/.
    "*.md",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[lint]
select = ["I"]
