# Generated by Django 6.1.1 on 2026-10-02 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("customer_id", models.CharField(blank=True, max_length=36)),
                ("payment_method_token", models.CharField(blank=True, max_length=35)),
                ("subscription_id", models.CharField(blank=True, max_length=10)),
                ("plan_id", models.CharField(blank=True, max_length=10)),
                ("plan_name", models.CharField(blank=True, max_length=50)),
                ("address_id", models.CharField(blank=True, max_length=2)),
                ("send_invoices", models.BooleanField(default=True)),
                ("invoice_email", models.EmailField(blank=True, max_length=254)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("renew_notice_date", models.DateField(blank=True, null=True)),
                ("setup_date", models.DateField(blank=True, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
