# Generated by Django 6.1.1 on 2026-10-03 00:01

from __future__ import annotations

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("data", models.BinaryField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="credentials", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("next_report_date", models.DateTimeField(blank=True, null=True)),
                (
                    "reports",
                    models.CharField(
                        choices=[("off", "Off"), ("daily", "Daily"), ("weekly", "Weekly"), ("monthly", "Monthly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                (
                    "nag_period",
                    models.DurationField(
                        choices=[
                            (datetime.timedelta(0), "Disabled"),
                            (datetime.timedelta(seconds=3600), "Hourly"),
                            (datetime.timedelta(days=1), "Daily"),
                        ],
                        default=datetime.timedelta(0),
                    ),
                ),
                ("next_nag_date", models.DateTimeField(blank=True, null=True)),
                ("ping_log_limit", models.IntegerField(default=100)),
                ("token", models.CharField(blank=True, max_length=128)),
                ("sort", models.CharField(default="created", max_length=20)),
                ("deletion_notice_date", models.DateTimeField(blank=True, null=True)),
                ("deletion_scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("last_active_date", models.DateTimeField(blank=True, null=True)),
                ("tz", models.CharField(default="UTC", max_length=36)),
                ("theme", models.CharField(blank=True, max_length=10, null=True)),
                ("totp", models.CharField(blank=True, max_length=32, null=True)),
                ("totp_created", models.DateTimeField(blank=True, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("api_key", models.CharField(blank=True, db_index=True, max_length=128)),
                ("api_key_readonly", models.CharField(blank=True, db_index=True, max_length=128)),
                ("badge_key", models.CharField(max_length=150, unique=True)),
                ("ping_key", models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ("show_slugs", models.BooleanField(default=False)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transfer_request_date", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(choices=[("r", "Read-only"), ("w", "Member"), ("m", "Manager")], default="w", max_length=1),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.project")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("user", "project"), name="accounts_member_no_duplicates")],
            },
        ),
    ]
