# Generated by Django 6.1.1 on 2026-10-02 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="call_limit",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="calls_sent",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="check_limit",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_call_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_sms_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="over_limit_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sms_limit",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sms_sent",
        ),
    ]
