# Generated by Django 6.1.1 on 2026-10-03 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="theme",
        ),
    ]
