# Generated by Django 6.1.1 on 2026-10-03 09:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_profile_theme"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="member",
            name="accounts_member_no_duplicates",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="deletion_notice_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="deletion_scheduled_date",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
