# Generated by Django 6.1.1 on 2026-10-03 21:20

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_delete_member_and_profile_deletion_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="badge_key",
        ),
    ]
