# Generated by Django 6.1.1 on 2026-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_project_badge_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="totp",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
