# Generated by Django 6.1.1 on 2026-10-04 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_totp_not_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ping_log_limit",
            field=models.IntegerField(
                default=100,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)],
            ),
        ),
    ]
