# Generated by Django 6.1.1 on 2026-10-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_profile_ping_log_limit_bounds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="show_slugs",
            field=models.BooleanField(default=True),
        ),
    ]
