# Generated by Django 6.1.1 on 2026-10-03 00:01

from __future__ import annotations

import datetime
import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenBucket",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.CharField(max_length=80, unique=True)),
                ("tokens", models.FloatField(default=1.0)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100)),
                ("slug", models.CharField(blank=True, max_length=100)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("desc", models.TextField(blank=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "kind",
                    models.CharField(
                        choices=[("simple", "Simple"), ("cron", "Cron"), ("oncalendar", "OnCalendar")],
                        default="simple",
                        max_length=10,
                    ),
                ),
                ("timeout", models.DurationField(default=datetime.timedelta(days=1))),
                ("grace", models.DurationField(default=datetime.timedelta(seconds=3600))),
                ("schedule", models.CharField(default="* * * * *", max_length=100)),
                ("tz", models.CharField(default="UTC", max_length=36)),
                ("filter_subject", models.BooleanField(default=False)),
                ("filter_body", models.BooleanField(default=False)),
                ("filter_http_body", models.BooleanField(default=False)),
                ("filter_default_fail", models.BooleanField(default=False)),
                ("start_kw", models.CharField(blank=True, max_length=200)),
                ("success_kw", models.CharField(blank=True, max_length=200)),
                ("failure_kw", models.CharField(blank=True, max_length=200)),
                ("methods", models.CharField(blank=True, max_length=30)),
                ("manual_resume", models.BooleanField(default=False)),
                ("badge_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("n_pings", models.IntegerField(default=0)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                ("last_start", models.DateTimeField(blank=True, null=True)),
                ("last_start_rid", models.UUIDField(null=True)),
                ("last_duration", models.DurationField(blank=True, null=True)),
                ("has_confirmation_link", models.BooleanField(default=False)),
                ("alert_after", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down"), ("new", "New"), ("paused", "Paused")], default="new", max_length=6
                    ),
                ),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.project")),
            ],
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100)),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "kind",
                    models.CharField(
                        choices=[("email", "Email"), ("group", "Group"), ("slack", "Slack"), ("webhook", "Webhook")], max_length=20
                    ),
                ),
                ("value", models.TextField(blank=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("last_notify", models.DateTimeField(blank=True, null=True)),
                ("last_notify_duration", models.DurationField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=200)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="accounts.project")),
                ("checks", models.ManyToManyField(to="api.check")),
            ],
        ),
        migrations.CreateModel(
            name="Flip",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField()),
                ("processed", models.DateTimeField(blank=True, null=True)),
                (
                    "old_status",
                    models.CharField(choices=[("up", "Up"), ("down", "Down"), ("new", "New"), ("paused", "Paused")], max_length=8),
                ),
                (
                    "new_status",
                    models.CharField(choices=[("up", "Up"), ("down", "Down"), ("new", "New"), ("paused", "Paused")], max_length=8),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("", "Unknown"), ("timeout", "Timeout"), ("fail", "Fail signal")], default="", max_length=8
                    ),
                ),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.check")),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("check_status", models.CharField(max_length=6)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("error", models.CharField(blank=True, max_length=200)),
                ("channel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.channel")),
                ("owner", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="api.check")),
            ],
            options={
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="Ping",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("n", models.IntegerField(null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("kind", models.CharField(blank=True, max_length=6, null=True)),
                ("scheme", models.CharField(default="http", max_length=10)),
                ("remote_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("ua", models.CharField(blank=True, max_length=200)),
                ("body_raw", models.BinaryField(null=True)),
                ("exitstatus", models.SmallIntegerField(null=True)),
                ("rid", models.UUIDField(null=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.check")),
            ],
        ),
        migrations.AddIndex(
            model_name="check",
            index=models.Index(
                condition=models.Q(("status", "down"), _negated=True), fields=["alert_after"], name="api_check_aa_not_down"
            ),
        ),
        migrations.AddIndex(
            model_name="check",
            index=models.Index(fields=["project_id", "slug"], name="api_check_project_slug"),
        ),
        migrations.AddIndex(
            model_name="flip",
            index=models.Index(condition=models.Q(("processed", None)), fields=["processed"], name="api_flip_not_processed"),
        ),
        migrations.AddIndex(
            model_name="flip",
            index=models.Index(fields=["owner", "created"], name="api_flip_owner_created"),
        ),
    ]
