# Generated by Django 6.1.1 on 2026-10-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="kind",
            field=models.CharField(
                choices=[("email", "Email"), ("group", "Group"), ("slack", "Slack"), ("webhook", "Webhook")], max_length=20
            ),
        ),
    ]
