# Generated by Django 6.1.1 on 2026-10-03 21:20

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="check",
            name="badge_key",
        ),
    ]
