# Generated by Django 6.1.1 on 2026-10-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_totp_not_null"),
        ("api", "0002_remove_check_badge_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="project",
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="accounts.project"),
        ),
        migrations.AlterField(
            model_name="flip",
            name="owner",
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="api.check"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="owner",
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to="api.check"),
        ),
        migrations.AlterField(
            model_name="ping",
            name="owner",
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to="api.check"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["owner", "created"], name="api_notification_owner_created"),
        ),
        migrations.AddIndex(
            model_name="ping",
            index=models.Index(fields=["owner", "n"], name="api_ping_owner_n"),
        ),
    ]
