# Generated by Django 6.1.1 on 2026-10-02 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0123_alter_channel_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ping",
            name="object_size",
        ),
    ]
