# Generated by Django 6.1.1 on 2026-10-02 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("host", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=100)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "notset"), (10, "debug"), (20, "info"), (30, "warning"), (40, "error"), (50, "critical")]
                    ),
                ),
                ("message", models.TextField()),
                ("traceback", models.TextField()),
            ],
        ),
    ]
